# Generated by Django 3.0.6 on 2020-05-23 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 19, 21, 47, 929162, tzinfo=utc)),
        ),
    ]
