# Generated by Django 3.0.6 on 2020-05-23 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200523_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'post_like')},
        ),
    ]
